### ISSUE TITLE
Error with color, maintainer, categories and keywords

### ISSUE THREAD

**Issue by brocolis** [brocolis/fpm-search#15]
1. color of the first 'Downloading ...' string
2. maintainer string truncated
3. categories and keywords empty

![fpm-search-bug](https://user-images.githubusercontent.com/5913872/112230673-0705fe80-8c14-11eb-91da-3a3405d0fa67.png)

**Comment by urbanjost** [comment]
If the compiler is new enough (there were problems with this in earlier gfortran versions, I am using 10)  you can make the maintainer array length allocatable, and reallocate when required while reading the JSON file.  Re-allocating can be expensive, but it seems you would have to read all the values once to get the maximum length, and then reread them again so something like this might be OK?
```diff
  diff --git a/app/json.f90 b/app/json.f90
index d988903..29dfe02 100644
@@ -122,7 +122,7 @@ subroutine fill(json, p, pkg)
     if (found) then
         pkg%maintainer_count = 1
-        allocate(pkg%maintainer(1))
+        allocate(character(len=len(str)) :: pkg%maintainer(1))
         pkg%maintainer(1) = str
     else
         call json%get(p, 'maintainer', q, found)
@@ -193,11 +193,14 @@ subroutine fill_maintainers(json, p, pkg)
     character(kind=json_CK,len=:), allocatable :: str
 
     pkg%maintainer_count = json%count(p)
-    allocate(pkg%maintainer(pkg%maintainer_count))
+    allocate(character(len=0) :: pkg%maintainer(pkg%maintainer_count))
 
     do i = 1, pkg%maintainer_count
         call json%get_child(p, i, q)
         call json%get(q, '@', str)
+        if(len(pkg%maintainer).lt.len(str))then
+          pkg%maintainer=[character(len=len(str)) :: pkg%maintainer] ! reallocate long enough to hold values
+        endif
         pkg%maintainer(i) = str
     end do
 
diff --git a/app/package_types.f90 b/app/package_types.f90
index 13d3d11..8b0f1ea 100644
@@ -7,7 +7,7 @@ type package_t
     character(len=64), allocatable :: author(:)
-    character(len=64), allocatable :: maintainer(:)
+    character(len=:),  allocatable :: maintainer(:)
     character(len=64), allocatable :: categories(:)
```

**Comment by urbanjost** [comment]
I can change the fixed-length variables in a similar manner if you would like.

**Comment by brocolis** [comment]
Hi @urbanjost, that's great, thank you. We can merge it!.

**Comment by brocolis** [comment]
> I can change the fixed-length variables in a similar manner if you would like.

Yes, I would like. Thank you @urbanjost.

**Comment by urbanjost** [comment]
OK.  Started it and hit an issue. Might be mine, might be compiler but it will take me a bit longer than I expected.  More details if I don't see it soon.

**Comment by brocolis** [comment]
Hi @urbanjost, found a bug in the _fill_keywords_, _fill_categories_ loops, I think it should be
```
   call json%get_child(p, i, q)
   call json%get(q, '@', str)
```
will try it later today.

**Comment by brocolis** [comment]
Partial fix https://github.com/brocolis/fpm-search/commit/f91313cb1a763124439317ae2f19304290eacddb

**Comment by brocolis** [comment]
Fixed https://github.com/brocolis/fpm-search/commit/21a92df2fc52c70ed0c8d2e12020c84cee98573c
