### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by brocolis** [brocolis/fpm-search#8]
Candidates

1. /etc/fpm-search.conf
2. $HOME/.fpm-search.conf

Format
1. plain text
2. ini
3. toml
4. lua

**Comment by urbanjost** [comment]
Although lua would be very flexible I'm wondering if there is a use case where you want it to be able to conditionally select files based on the system type or the value of $COMPILER or something fancy like that. I am not sure if you want fpm-search to maintain the file with some option like --save or --delete in which case the user would not have to edit the file and you could use anything you wanted or not.  I think plain text would work and a user could edit it very easily; you already are working with TOML and JSON; adding lua or INI seems to complicate it. TOML is already used by fpm(1) and the TOML Fortran interface already needs maintained and used for use with fpm(1) so I would think plain text; maybe LUA. Wondering if you think fpm(1) will change to lua(3) or INI(3). NAMELIST(3f) would work too. Would some of those be easier than I think? Are you thinking of being compatible with some other programs or package managers (I have no idea what they use, though).  Those locations seem useful enough I wonder if you don't just search for them both and use them if they exist; maybe even and a list of directories to search via an environment variable like FPM_SEARCH_PATH?

**Comment by brocolis** [comment]
There are many good ideas here, thank you @urbanjost. OK I think we can start with a plain text file and then we can switch to another format, if there is a good reason. At this stage we can try different options and see what happens.

I would propose this simple format for the config file.

`label=URL`

Example
```
base=https://github.com/fortran-lang/fpm-registry/raw/master/index.json
my1=http://localhost/path/index.json
my2=http://server/path/index.json
```

_fpm-search_ will read both files _/etc/fpm-search.conf_ and _$HOME/.fpm-search.conf_ then read the environment variable FPM_SEARCH_PATH.

**Comment by urbanjost** [comment]
I have a function called lookfor(3f) in [M_IO](https://github.com/urbanjost/M_io) that might be worth looking at (as-is it calls at least several other modules).  It parses an environment variable and looks if the file exists or not without using C POSIX routines (that can check more thoroughly that the file is readable and such but is not portable to MSWIndows).
