### ISSUE TITLE
Add M_match

### ISSUE THREAD

**Issue by brocolis** [brocolis/fpm-search#9]
Remove libpcre

**Comment by urbanjost** [comment]
That would be great from my perspective :>; but note M_match currently is BRE (Basic Regular Expressions) so you would have to parse on "|" and do multiple matches yourself. I see in your example you do 'NAME1|NAME2'. Using BREs you would have to split that on the "|" and do a search on NAME1 and then NAME2 yourself.

**Comment by brocolis** [comment]
@urbanjost We can temporarily remove libpcre and update the help string. I think we can drop this feature 'NAME1|NAME2' for now and revisit it later.
